# Generated by Django 5.2.1 on 2025-06-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(default='Sin descripcion', max_length=300, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
