# Generated by Django 5.2.1 on 2025-06-13 20:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_categoria_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('correo_electronico', models.CharField(max_length=110, verbose_name='Correo Electroncio ')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CR', verbose_name='Teléfono')),
            ],
        ),
    ]
