# Generated by Django 5.2.1 on 2025-06-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tipo_venta_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio_unitario',
        ),
    ]
