# Generated by Django 5.2.1 on 2025-06-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_detalleventa_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='autor',
            field=models.CharField(default='Sin autor', max_length=150, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripcion', max_length=500, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
